begin;

delete from inventory_items;
delete from market_prices;
delete from products;
delete from categories;

insert into markets (code, name, currency, locale)
values
  ('PE', 'Perú', 'PEN', 'es-PE'),
  ('BO', 'Bolivia', 'BOB', 'es-BO')
on conflict (code) do update set
  name = excluded.name,
  currency = excluded.currency,
  locale = excluded.locale,
  is_active = true,
  updated_at = now();

insert into categories (slug, name, sort_order)
values
  ('video', 'Video y televisión', 10),
  ('musica', 'Música y audio', 20),
  ('gaming', 'Videojuegos', 30),
  ('inteligencia-artificial', 'Inteligencia artificial', 40),
  ('productividad', 'Productividad', 50),
  ('seguridad', 'Seguridad y VPN', 60),
  ('cursos-bienestar', 'Cursos y bienestar', 70)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

insert into products (
  slug, category_id, service_name, plan_name, description, seller_label,
  billing_label, delivery_label, accent_color, accent_soft_color, artwork_class, mark
)
values
  ('netflix-individual', (select id from categories where slug = 'video'), 'Netflix', 'Individual', 'Películas, series y documentales bajo suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'N'),
  ('disney-individual', (select id from categories where slug = 'video'), 'Disney+', 'Individual', 'Películas, series y contenido de Disney.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'D+'),
  ('apple-tv-individual', (select id from categories where slug = 'video'), 'Apple TV+', 'Individual', 'Series y películas originales de Apple.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'TV'),
  ('max-individual', (select id from categories where slug = 'video'), 'Max', 'Individual', 'Películas, series y producciones de HBO.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'M'),
  ('amazon-prime-video-individual', (select id from categories where slug = 'video'), 'Amazon Prime Video', 'Individual', 'Películas, series y producciones originales.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'PV'),
  ('paramount-individual', (select id from categories where slug = 'video'), 'Paramount+', 'Individual', 'Películas, series y contenido de Paramount.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'P+'),
  ('hulu-individual', (select id from categories where slug = 'video'), 'Hulu', 'Individual', 'Series, películas y televisión bajo demanda.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'H'),
  ('peacock-individual', (select id from categories where slug = 'video'), 'Peacock', 'Individual', 'Series, películas y contenido de NBCUniversal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'P'),
  ('crunchyroll-fan-mega-fan', (select id from categories where slug = 'video'), 'Crunchyroll', 'Fan / Mega Fan', 'Anime y contenido asiático bajo suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'CR'),
  ('mubi-individual', (select id from categories where slug = 'video'), 'MUBI', 'Individual', 'Cine independiente y películas seleccionadas.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'MU'),
  ('dazn-individual', (select id from categories where slug = 'video'), 'DAZN', 'Individual', 'Eventos y contenido deportivo en streaming.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'DZ'),
  ('viki-pass-standard-plus', (select id from categories where slug = 'video'), 'Viki Pass', 'Standard / Plus', 'Dramas y entretenimiento asiático.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'VK'),
  ('vix-premium-individual', (select id from categories where slug = 'video'), 'ViX Premium', 'Individual', 'Películas, series y televisión en español.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'VX'),
  ('claro-video-individual', (select id from categories where slug = 'video'), 'Claro video', 'Individual', 'Películas y series bajo demanda.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'CV'),
  ('movistar-tv-app-individual', (select id from categories where slug = 'video'), 'Movistar TV App', 'Individual', 'Televisión y entretenimiento por internet.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'MT'),
  ('dgo-directv-individual', (select id from categories where slug = 'video'), 'DGO / DIRECTV', 'Individual', 'Televisión en vivo y contenido bajo demanda.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'DG'),
  ('zapping-individual', (select id from categories where slug = 'video'), 'Zapping', 'Individual', 'Canales de televisión por internet.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'Z'),
  ('globoplay-individual', (select id from categories where slug = 'video'), 'Globoplay', 'Individual', 'Series, novelas y contenido brasileño.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'GL'),
  ('telecine-individual', (select id from categories where slug = 'video'), 'Telecine', 'Individual', 'Catálogo de películas por suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'TC'),
  ('starz-individual', (select id from categories where slug = 'video'), 'Starz', 'Individual', 'Películas y series originales.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'SZ'),
  ('curiositystream-individual', (select id from categories where slug = 'video'), 'CuriosityStream', 'Individual', 'Documentales de ciencia, historia y tecnología.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'CS'),
  ('nebula-individual', (select id from categories where slug = 'video'), 'Nebula', 'Individual', 'Contenido educativo de creadores independientes.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'NB'),
  ('rakuten-viki-rakuten-tv-individual', (select id from categories where slug = 'video'), 'Rakuten Viki / Rakuten TV', 'Individual', 'Películas, series y entretenimiento asiático.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-video', 'RK'),
  ('spotify-premium-individual', (select id from categories where slug = 'musica'), 'Spotify Premium', 'Individual', 'Música y podcasts sin anuncios.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'SP'),
  ('apple-music-individual', (select id from categories where slug = 'musica'), 'Apple Music', 'Individual', 'Música en streaming y audio espacial.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'AM'),
  ('youtube-music-premium-individual', (select id from categories where slug = 'musica'), 'YouTube Music Premium', 'Individual', 'Música sin anuncios y reproducción en segundo plano.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'YM'),
  ('amazon-music-unlimited-individual', (select id from categories where slug = 'musica'), 'Amazon Music Unlimited', 'Individual', 'Catálogo musical bajo suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'AU'),
  ('deezer-premium-individual', (select id from categories where slug = 'musica'), 'Deezer Premium', 'Individual', 'Música sin anuncios y reproducción sin conexión.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'DZ'),
  ('tidal-individual', (select id from categories where slug = 'musica'), 'TIDAL', 'Individual', 'Música en alta calidad.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'TD'),
  ('qobuz-individual', (select id from categories where slug = 'musica'), 'Qobuz', 'Individual', 'Música en alta resolución.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'Q'),
  ('soundcloud-go-individual', (select id from categories where slug = 'musica'), 'SoundCloud Go+', 'Individual', 'Música y contenido de creadores sin anuncios.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'SC'),
  ('audible-individual', (select id from categories where slug = 'musica'), 'Audible', 'Individual', 'Audiolibros y contenido hablado.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'A'),
  ('storytel-individual', (select id from categories where slug = 'musica'), 'Storytel', 'Individual', 'Audiolibros y libros digitales.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'ST'),
  ('podimo-individual', (select id from categories where slug = 'musica'), 'Podimo', 'Individual', 'Podcasts y audiolibros exclusivos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'PO'),
  ('tunein-premium-individual', (select id from categories where slug = 'musica'), 'TuneIn Premium', 'Individual', 'Radio, noticias, música y deportes.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'TI'),
  ('apple-podcasts-subscriptions-individual', (select id from categories where slug = 'musica'), 'Apple Podcasts Subscriptions', 'Individual', 'Canales y programas de podcast por suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-musica', 'AP'),
  ('xbox-game-pass-individual', (select id from categories where slug = 'gaming'), 'Xbox Game Pass', 'Individual', 'Catálogo de videojuegos para consola y PC.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'XB'),
  ('playstation-plus-individual', (select id from categories where slug = 'gaming'), 'PlayStation Plus', 'Individual', 'Juegos, multijugador y beneficios para PlayStation.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'PS'),
  ('nintendo-switch-online-individual', (select id from categories where slug = 'gaming'), 'Nintendo Switch Online', 'Individual', 'Juego en línea y catálogo clásico de Nintendo.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'NS'),
  ('ea-play-individual', (select id from categories where slug = 'gaming'), 'EA Play', 'Individual', 'Juegos y beneficios de Electronic Arts.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'EA'),
  ('ubisoft-individual', (select id from categories where slug = 'gaming'), 'Ubisoft+', 'Individual', 'Catálogo de juegos de Ubisoft.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'U+'),
  ('geforce-now-individual', (select id from categories where slug = 'gaming'), 'GeForce NOW', 'Individual', 'Videojuegos en la nube.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'GN'),
  ('apple-arcade-individual', (select id from categories where slug = 'gaming'), 'Apple Arcade', 'Individual', 'Juegos para dispositivos Apple.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'AA'),
  ('google-play-pass-individual', (select id from categories where slug = 'gaming'), 'Google Play Pass', 'Individual', 'Juegos y aplicaciones para Android.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'GP'),
  ('discord-nitro-individual', (select id from categories where slug = 'gaming'), 'Discord Nitro', 'Individual', 'Beneficios y personalización para Discord.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'DN'),
  ('roblox-premium-robux-individual', (select id from categories where slug = 'gaming'), 'Roblox Premium / Robux', 'Individual', 'Membresía y saldo digital para Roblox.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'RB'),
  ('fortnite-v-bucks-individual', (select id from categories where slug = 'gaming'), 'Fortnite / V-Bucks', 'Individual', 'Saldo digital para contenido de Fortnite.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'FN'),
  ('riot-points-valorant-individual', (select id from categories where slug = 'gaming'), 'Riot Points / VALORANT', 'Individual', 'Saldo digital para juegos de Riot.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'RP'),
  ('minecraft-realms-individual', (select id from categories where slug = 'gaming'), 'Minecraft Realms', 'Individual', 'Mundos privados de Minecraft bajo suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-gaming', 'MC'),
  ('chatgpt-plus', (select id from categories where slug = 'inteligencia-artificial'), 'ChatGPT', 'Plus', 'Asistente de inteligencia artificial de OpenAI.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CG'),
  ('chatgpt-pro', (select id from categories where slug = 'inteligencia-artificial'), 'ChatGPT', 'Pro', 'Acceso ampliado a herramientas de OpenAI.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CG'),
  ('google-ai-plus', (select id from categories where slug = 'inteligencia-artificial'), 'Google AI', 'Plus', 'Herramientas de IA y almacenamiento de Google.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'GA'),
  ('google-ai-pro-gemini-pro', (select id from categories where slug = 'inteligencia-artificial'), 'Google AI Pro / Gemini', 'Pro', 'Funciones avanzadas de Gemini y Google One.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'GM'),
  ('google-ai-ultra', (select id from categories where slug = 'inteligencia-artificial'), 'Google AI', 'Ultra', 'Nivel avanzado de herramientas de IA de Google.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'GU'),
  ('claude-pro', (select id from categories where slug = 'inteligencia-artificial'), 'Claude', 'Pro', 'Asistente de inteligencia artificial de Anthropic.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CL'),
  ('claude-max', (select id from categories where slug = 'inteligencia-artificial'), 'Claude', 'Max', 'Acceso ampliado al asistente Claude.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CL'),
  ('microsoft-copilot-pro', (select id from categories where slug = 'inteligencia-artificial'), 'Microsoft Copilot', 'Pro', 'Asistente de IA para productividad personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CP'),
  ('perplexity-pro', (select id from categories where slug = 'inteligencia-artificial'), 'Perplexity', 'Pro', 'Búsqueda y respuestas asistidas por IA.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'PX'),
  ('grok-x-premium-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Grok / X Premium', 'Individual', 'Funciones de IA integradas en X.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'GR'),
  ('poe-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Poe', 'Individual', 'Acceso a distintos asistentes de inteligencia artificial.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'PO'),
  ('midjourney-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Midjourney', 'Individual', 'Generación de imágenes mediante IA.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'MJ'),
  ('runway-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Runway', 'Individual', 'Generación y edición audiovisual con IA.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'RW'),
  ('adobe-firefly-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Adobe Firefly', 'Individual', 'Generación creativa integrada con Adobe.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'AF'),
  ('canva-ai-magic-studio-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Canva AI / Magic Studio', 'Individual', 'Herramientas creativas de IA dentro de Canva.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CA'),
  ('notion-ai-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Notion AI', 'Individual', 'Asistencia de escritura y organización en Notion.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'NA'),
  ('github-copilot-individual', (select id from categories where slug = 'inteligencia-artificial'), 'GitHub Copilot', 'Individual', 'Asistente de programación con inteligencia artificial.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'GH'),
  ('cursor-pro', (select id from categories where slug = 'inteligencia-artificial'), 'Cursor', 'Pro', 'Editor de código asistido por IA.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'CU'),
  ('replit-core', (select id from categories where slug = 'inteligencia-artificial'), 'Replit', 'Core', 'Desarrollo y asistencia de programación en la nube.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'RE'),
  ('mistral-le-chat-pro', (select id from categories where slug = 'inteligencia-artificial'), 'Mistral Le Chat', 'Pro', 'Asistente de inteligencia artificial de Mistral.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'ML'),
  ('leonardo-ai-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Leonardo AI', 'Individual', 'Generación de imágenes y recursos creativos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'LA'),
  ('ideogram-individual', (select id from categories where slug = 'inteligencia-artificial'), 'Ideogram', 'Individual', 'Generación de imágenes y texto visual.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'ID'),
  ('elevenlabs-individual', (select id from categories where slug = 'inteligencia-artificial'), 'ElevenLabs', 'Individual', 'Generación y procesamiento de voz mediante IA.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-inteligencia-artificial', 'EL'),
  ('microsoft-365-personal', (select id from categories where slug = 'productividad'), 'Microsoft 365', 'Personal', 'Aplicaciones de Office y almacenamiento personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'M3'),
  ('google-one-individual', (select id from categories where slug = 'productividad'), 'Google One', 'Individual', 'Almacenamiento y beneficios para la cuenta Google.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'G1'),
  ('icloud-individual', (select id from categories where slug = 'productividad'), 'iCloud+', 'Individual', 'Almacenamiento y privacidad para dispositivos Apple.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'IC'),
  ('dropbox-plus', (select id from categories where slug = 'productividad'), 'Dropbox', 'Plus', 'Almacenamiento y sincronización de archivos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'DB'),
  ('dropbox-professional', (select id from categories where slug = 'productividad'), 'Dropbox', 'Professional', 'Herramientas avanzadas de almacenamiento personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'DB'),
  ('adobe-creative-cloud-individual', (select id from categories where slug = 'productividad'), 'Adobe Creative Cloud', 'Individual', 'Aplicaciones creativas de Adobe.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'AC'),
  ('canva-pro', (select id from categories where slug = 'productividad'), 'Canva', 'Pro', 'Diseño y creación de contenido visual.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'CV'),
  ('notion-plus', (select id from categories where slug = 'productividad'), 'Notion', 'Plus', 'Notas, documentos y organización personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'NO'),
  ('zoom-pro', (select id from categories where slug = 'productividad'), 'Zoom', 'Pro', 'Videollamadas y reuniones ampliadas.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'ZM'),
  ('dropbox-sign-individual', (select id from categories where slug = 'productividad'), 'Dropbox Sign', 'Individual', 'Firma electrónica de documentos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'DS'),
  ('docusign-individual', (select id from categories where slug = 'productividad'), 'DocuSign', 'Individual', 'Firma y gestión electrónica de documentos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'DC'),
  ('evernote-personal', (select id from categories where slug = 'productividad'), 'Evernote', 'Personal', 'Notas y organización personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'EV'),
  ('evernote-professional', (select id from categories where slug = 'productividad'), 'Evernote', 'Professional', 'Funciones avanzadas de notas y productividad.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'EV'),
  ('todoist-pro', (select id from categories where slug = 'productividad'), 'Todoist', 'Pro', 'Gestión personal de tareas y proyectos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-productividad', 'TD'),
  ('1password-individual', (select id from categories where slug = 'seguridad'), '1Password', 'Individual', 'Gestión segura de contraseñas personales.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', '1P'),
  ('bitwarden-premium', (select id from categories where slug = 'seguridad'), 'Bitwarden', 'Premium', 'Gestión de contraseñas y autenticación.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'BW'),
  ('nordpass-premium', (select id from categories where slug = 'seguridad'), 'NordPass', 'Premium', 'Gestor personal de contraseñas.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'NP'),
  ('dashlane-premium', (select id from categories where slug = 'seguridad'), 'Dashlane', 'Premium', 'Contraseñas y protección de identidad.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'DL'),
  ('nordvpn-individual', (select id from categories where slug = 'seguridad'), 'NordVPN', 'Individual', 'Red privada virtual para navegación personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'NV'),
  ('surfshark-individual', (select id from categories where slug = 'seguridad'), 'Surfshark', 'Individual', 'VPN y herramientas de privacidad.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'SS'),
  ('expressvpn-individual', (select id from categories where slug = 'seguridad'), 'ExpressVPN', 'Individual', 'Red privada virtual para uso personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'EX'),
  ('proton-unlimited-individual', (select id from categories where slug = 'seguridad'), 'Proton Unlimited', 'Individual', 'Privacidad, correo, almacenamiento y VPN.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'PU'),
  ('proton-vpn-individual', (select id from categories where slug = 'seguridad'), 'Proton VPN', 'Individual', 'Red privada virtual enfocada en privacidad.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-seguridad', 'PV'),
  ('duolingo-super', (select id from categories where slug = 'cursos-bienestar'), 'Duolingo', 'Super', 'Aprendizaje de idiomas sin anuncios.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'DU'),
  ('duolingo-max', (select id from categories where slug = 'cursos-bienestar'), 'Duolingo', 'Max', 'Aprendizaje de idiomas con funciones ampliadas.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'DU'),
  ('coursera-plus', (select id from categories where slug = 'cursos-bienestar'), 'Coursera', 'Plus', 'Cursos y certificaciones en línea.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'CO'),
  ('udemy-personal', (select id from categories where slug = 'cursos-bienestar'), 'Udemy', 'Personal', 'Catálogo personal de cursos en línea.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'UD'),
  ('skillshare-individual', (select id from categories where slug = 'cursos-bienestar'), 'Skillshare', 'Individual', 'Cursos creativos y profesionales.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'SK'),
  ('masterclass-individual', (select id from categories where slug = 'cursos-bienestar'), 'MasterClass', 'Individual', 'Clases impartidas por especialistas reconocidos.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'MC'),
  ('scribd-everand-individual', (select id from categories where slug = 'cursos-bienestar'), 'Scribd / Everand', 'Individual', 'Libros, audiolibros y documentos digitales.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'SE'),
  ('kindle-unlimited-individual', (select id from categories where slug = 'cursos-bienestar'), 'Kindle Unlimited', 'Individual', 'Catálogo de libros digitales por suscripción.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'KU'),
  ('headspace-individual', (select id from categories where slug = 'cursos-bienestar'), 'Headspace', 'Individual', 'Meditación y bienestar personal.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'HS'),
  ('calm-premium', (select id from categories where slug = 'cursos-bienestar'), 'Calm', 'Premium', 'Meditación, sueño y relajación.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'CM'),
  ('strava-individual', (select id from categories where slug = 'cursos-bienestar'), 'Strava', 'Individual', 'Seguimiento y análisis de actividad deportiva.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'SV'),
  ('fitbit-premium-individual', (select id from categories where slug = 'cursos-bienestar'), 'Fitbit Premium', 'Individual', 'Métricas y programas de bienestar.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'FB'),
  ('apple-fitness-individual', (select id from categories where slug = 'cursos-bienestar'), 'Apple Fitness+', 'Individual', 'Entrenamientos y bienestar para dispositivos Apple.', 'DoraPass', '', 'Precio por confirmar', '#155EEF', '#F3F4F6', 'art-cursos-bienestar', 'FT');

update products
set image_path = '/platforms/' || slug || '.png',
    image_alt = 'Logo de ' || service_name,
    seller_label = 'DoraPass',
    updated_at = now();

commit;
